<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contabilidad [
    <!ELEMENT contabilidad (apunte*)>
    <!ELEMENT apunte ((ingreso | gasto)+, fecha, cantidad, concepto)>
    <!ELEMENT ingreso EMPTY>
    <!ELEMENT gasto EMPTY>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT concepto (#PCDATA)>
]>
<contabilidad>
    <apunte>
        <ingreso />
        <fecha> 14 de marzo de 2018 </fecha>
        <cantidad> 1080€ </cantidad>
        <concepto> Nómina </concepto>
    </apunte>
    <apunte>
        <gasto />
        <fecha> 28 de febrero de 2018 </fecha>
        <cantidad> 75€ </cantidad>
        <concepto> Recibo Comunidad </concepto>
    </apunte>
</contabilidad>