<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Libro [
    <!ELEMENT Libro (Titulo, Seccion, SubSeccion?, Contenido, Copyright)>
    <!ATTLIST Libro Catalogo ID #REQUIRED>
    <!ELEMENT Titulo (#PCDATA)>
    <!ELEMENT Seccion (#PCDATA)>
    <!ELEMENT SubSeccion (#PCDATA)>
    <!ELEMENT Contenido ((Capitulo+)|(Capitulo+, Separacion?)+)>
    <!ELEMENT Capitulo (Tema+)>
    <!ATTLIST Capitulo materia (XML|XHTML) "XML">
    <!ELEMENT Tema (#PCDATA)>
    <!ELEMENT Separacion EMPTY>
    <!ELEMENT Copyright (#PCDATA)>
]>
<Libro Catalogo="cmg">
    <Titulo>Example</Titulo>
    <Seccion>Misterio</Seccion>
    <SubSeccion>Fantasia</SubSeccion>
    <Contenido>
        <Capitulo>
            <Tema>Introduccion</Tema>
        </Capitulo>
        <Capitulo>
            <Tema>Nudo</Tema>
        </Capitulo>
        <Capitulo>
            <Tema>Desenlace</Tema>
        </Capitulo>
    </Contenido>
    <Copyright>Carlos Manso, 2022</Copyright>
</Libro>