<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musicos [
    <!ELEMENT musicos (musico*)>
    <!ELEMENT musico ((nombre | apodo),nacimiento)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apodo (#PCDATA)>
    <!ELEMENT nacimiento (#PCDATA)>
]>
<musicos>
    <musico>
        <apodo> El cura pelirrojillo </apodo>
        <nacimiento> 4 de marzo de 1678 </nacimiento>
    </musico>
    <musico>
        <nombre> Johann Sebastian Bach </nombre>
        <nacimiento>21 de marzo de 1685</nacimiento>
    </musico>
</musicos>