=== dag45684/Mark-I/U2/DTD varios/Conciertos.dtd
<!ELEMENT conciertos (concierto, contacto, correo)+>
<!ELEMENT concierto (diaHora, duracion, cache, asunto)>
<!ATTLIST concierto telonerosSiNo (si|no) #REQUIRED>
<!ELEMENT diaHora (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT cache (#PCDATA)>
<!ELEMENT asunto (#PCDATA)> <!--Aplica al asunto en los tag de correo y concierto-->
<!ELEMENT contacto (nombre, telefonoInternacional, url)>
<!ELEMENT nombre EMPTY>
<!ATTLIST nombre idioma (es|it|dk|pt) #REQUIRED>
<!ELEMENT telefonoInternacional (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT correo (remitente, destinatario*, asunto, cuerpo)>
<!ATTLIST correo leidoSiNo (si|no) #REQUIRED>
<!ELEMENT remitente (#PCDATA)>
<!ELEMENT destinatario (#PCDATA)>
<!ELEMENT cuerpo (#PCDATA)>

=== dag45684/Mark-I/U2/DTD varios/DTD2Conciertos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE conciertos SYSTEM "Conciertos.dtd">
<conciertos>
    <concierto telonerosSiNo="no">
        <diaHora>2020-12-17T09:30:47</diaHora>
        <duracion>P0Y0M0DT01H30M</duracion>
        <cache>15000</cache>
        <asunto>Aqui ira el nombre del concierto</asunto>
    </concierto>
    <contacto>
        <nombre idioma="es"/>
        <telefonoInternacional>+44 123 456789</telefonoInternacional>
        <url>text</url>
    </contacto>
    <correo leidoSiNo="no">
        <remitente>correo@dominio.jcm</remitente>
        <destinatario>correo@dominio.jcm</destinatario>
        <destinatario>correo@dominio.jcm</destinatario>
        <asunto>string</asunto>
        <cuerpo>string</cuerpo>
    </correo>
</conciertos>
